=== British-Oceanographic-Data-Centre/bblocks-sta/build/annotated/api/sta/HistoricalLocations/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "HistoricalLocation object",
  "description": "Schema for HistoricalLocation entity in OGC SensorThings API 1.3",
  "type": "object",
  "properties": {
    "@iot.id": {
      "description": "The Id of the HistoricalLocation",
      "x-jsonld-id": "@id"
    },
    "@iot.selfLink": {
      "type": "string",
      "description": "The direct link to the HistoricalLocation entity",
      "x-jsonld-id": "http://www.opengis.net/def/rel/iana/1.0/self"
    },
    "time": {
      "type": "string",
      "format": "date-time",
      "description": "The time when the Thing was at the Location (PROV startedAtTime).",
      "x-jsonld-id": "http://www.w3.org/ns/prov#startedAtTime"
    },
    "Thing@iot.navigationLink": {
      "type": "string",
      "description": "Reference link to the related Thing entity",
      "x-jsonld-id": "http://www.w3.org/ns/prov#entity",
      "x-jsonld-type": "@id"
    },
    "Locations@iot.navigationLink": {
      "type": "string",
      "description": "Reference link to the related Location entities",
      "x-jsonld-id": "http://www.opengis.net/ont/geosparql#hasGeometry",
      "x-jsonld-type": "@id"
    }
  },
  "required": [
    "@iot.id",
    "@iot.selfLink",
    "Thing@iot.navigationLink",
    "Locations@iot.navigationLink"
  ],
  "x-jsonld-prefixes": {
    "orel": "http://www.opengis.net/def/rel/",
    "prov": "http://www.w3.org/ns/prov#",
    "geo": "http://www.opengis.net/ont/geosparql#"
  }
}

=== British-Oceanographic-Data-Centre/bblocks-sta/build/tests/api/sta/HistoricalLocations/example_1_1.json
{
  "@iot.id": 1,
  "@iot.selfLink": "http://example.org/v1.1/HistoricalLocations(1)",
  "time": "2024-09-01T12:00:00Z",
  "Thing@iot.navigationLink": "http://example.org/v1.1/HistoricalLocations(1)/Thing",
  "Locations@iot.navigationLink": "http://example.org/v1.1/HistoricalLocations(1)/Locations"
}
